version: '3'

services:
  app:
    build: .
    ports:
    - "8888:3000"
    volumes:
    - ".:/app/src/package-manager"
    working_dir: /app/src/package-manager
    command: bash -c "go build -o main && ./main"